env:
  global:
    - secure: HPW5ytwT3TJp1gt/3Kj+v58Q89XqCbAWFRtxnyui1CI08i3qyll1AHrrBHdyXF1bvNRIVK/YoyaU3T7/oWdxH8Ci2sMVvDA8d0rz/DhoIFWkhHaL7y//CBMQjA8teIA6FjAf13cDH4+HgDKDTc9v9/SFYWyUV9kYShZ/YyU60wQyKZ1qM/UpUV0Na7OclMqYLmx775TVVLLf3khS6HhyyE0pbmOcC43OT1szIAh5yh5dsPWWoJbxNNFceVxY8ePs7A+iJh7Bbaqapp9CG0idcZkmPYujHv4s83BYZd9i1U96Q/hwyIq0H6U/DkSl/UGJHu+3Qnetppb01ewfpSPkN417+yP6hiuSURKeJcbs4Gt6JOw6/CfV9hpA0MdBypJLvFwttGMIePQ7LX1t7J6poKabZTss74y9h0uq0tkE+luGzz6nyANanIlOF7RRA+f7trRZQnhXyLb65jTAB+YAlhvF6VOAm3XF+myVe/pSLiPx6eRahFybML4bUsAUmUBp/s9oAeSPYrbDZ7pKKkKhOQuIPivBB5qDzLKUkmOJsQOkCyH99bg6bzA2vEIpShSK13R1EgpLz1zdnOg6FtSLCevFcEB4yZwOSOMou1C6O2omrHd+Fn1JF3fk4GicOD20b4R42blDLkroTw4DdsRv2Q8p+nrHUDjfCGgr1YVcAyI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/pl-host-file
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
