env:
  global:
    - secure: rYfve9NKR7E7CQcU52hkQd2THVM/iKnIsVoRf2Nfmraex+p8YNgzG/gnV4QSNu65Y8PUfLgb2Rq9uu73g2N1Kg+Ie0D/25a8L22oJ0BPqpLa09cDU+rqD75wPnFRZaxDEthgZBfVD3lAnYs2IPF4dT7K8kD0ChG5Pfb7CqJgJBy2T45LLL3asC9nmkOhUQsCqp6H5VHcAd/yIDKTc530tX0wx3pcTmQ9OpE4Q5qRl9ULkSb5k9e+bxX1AL/AQSgVABD3kDzhg+Zkod3UHVKBL/rUwFUIBzcvEn8FZSfV8Lq0bHgIA7mxTriFxF9xAdyzz4rpuuI50x0C6O9Pnv7mqS90OjifdWv1m8utNe4AQFjinKiaht6cnASHHm6Tb0dzXKViR94NV3CD3+5TfVs2pc3wrmP+3U/RWhNRFA3z4X7BIyXKOVy7rjRZJobP5gXxoLVA8MMX6qFbUOhy1jykAk7okvqKgHOHRR3w+Mg2VnlljHGSJVNUFDAOBZJSw+P9WlmZprhOG/TqFHQ4mY7S8olZb6MV/xrMar23zQK9KGr1Pm6rwaNNk6JUjtQkl5jXjm7TDz3ejpbr9w5c0z/DfOwIeXBAXpSgOIDHIsjc54rgxfTU4hKtzAWao9CbQoTc/obosRcnj1gC9v8sfmROoF4CKWXW5d5Yd8GXcee7x/Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/pl-host-file
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
