env:
  global:
    - secure: DxKwlyAVjpRJ5yMgH/st/zFZuE6WJ8222IHFUwasJb+tDm3b9GMvfnr4YrIa8Zk/b8lptYIugD/lAP/69xB9J6V+JalHMpq5Xw1gH9YWuXCj2EgCfGx8h9U2Z+1+3caRE1kTB2KQqTIjnSJ7c/83SqlzzSCgLTzVfZwwanJ3xI9NWp3/Qx7fH6iccJebDnEj3vqJb3b5+7Day98CFc+607/+IVah6bGSOL5ABiq+y780TIWE80xEH7lNnMcLZGXXqCVYcOTMLP9StUps+he5cW8nw3aQpxwxQ2crDqOJkECettlNniDPMC9SM4nQ5fsjbBa2Qf0k3mZx9Bekkc4r1m1GxLI6NHNA9IhMuyPBI3a9iZ8Lr3ROXIYa4u9uX45j4dT6a3B5U+NIN5Xv8vziMrZr7sV0PnT3TPtkyxjtZNcSY1tP82mojtnroVEh7lmnv3hU2KIKUB3NjXn26Vf3f+q+rT1MIMeW22Hq1l4nKtM1VdZZFOyODSNH67kqV+uavXz4AD6VOL64JTn3FGbhir4nTfbjk8BBALDll6JQmy8IL4uFL1GwX3s04cMX525lnXV6BKm6QRnYFqLE0TTQRHTJEsOJglXBFeN6RNDZgwXM6dCt7so6hlbTAyYxKBzq6IP+kNne/0zxivCxjWNaElxUXvRtJMId51uu28HzsJQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/pl-host-file
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
