env:
  global:
    - secure: lxh7uBSEJN4qMtolHLIw5n1A5LfQPxSyVc2L33F2uAuaxQTHh9Nu+0ksPSnwho1HE1/OdFDM/TZpeIbHihqIAxqfmnI08S4CQaOPuxNB0ZDBfO+EQlBuCJQb1XnBmllXVwLRUvlHk/eeb8PgJMf3mNzMnHNsJck6ebAG8qtz1XbyFs0xRt30ht94mvfTRaAKxBSGVt2zxrq+Q02au8CDfoxoRgtbLPgAMNmYvTOSZ3zrsCOkAjuf0w1gGiSlKxZfTvY8Jo7hsFlrzuItrDxWF53HTjXQbXEL1OiLXGYlu2DECtfNu3SqrScG2coBVDMDj2TCb+9a6e+Qx9k6u8O4m+DqZd7hTO+8nFwCWwdWrKzCUxsqOH1D0bdWmuZnPBoixRwAPfHMwmW1okNmqSX6p3sFNxytzqgoZV24LncTvmvktio1sWKYsk3jAK6UykzyL8aZ+z79rZscMWkb1PIZ3I15d40ogK/aGw1eMRNnSQuQlKiq8feQSAtTjqGcJIaCBGT3Ok+3hI1GHIv/9FfV6O7ne7mw+RWUahr9TnCHE29izkJD6xnQT7RplrV/7jRU1oIb0pYbGSO+4XVYDDQmmeJIBQcg8miJLVNXSy+GJn934QZclWxds+xRjlM2bsuW/zqsmlGS6sUF2r9WnbVjSQk3OlUXvZL390yq/ff1ON0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/pl-host-file
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
