env:
  global:
    - secure: rqYTsGmQSzQD/LrYZeJ6jNIZHE/DvzmHnQmJwMjjUPna60NAPbTkDWTpKI+pBD5R9zVsPFR/4NpxfYu8YU5633oD9k1+vkg//OLMRug0x1DQJptn2JGTcQScEhK5Aj8Nqydpi61UhccRbZz1dePZNoNHfxCuhOlmcT8JQt6eTbPRJmaxqwCbjR0RSofeqOZr8gCS+yMLLGo0J0xq3NsUudbqV/DMVe2AIVlxnoajttnN/3tTYnrojIMTnrbmPm5fa/RPxVOD4Th6p86mZMznq16P19kOP+kKIu42Zmso24dGgPho2Lsw3oYrwR98xHqAfvyb0tTZKEiDJfXRefq/L5SWJXUaXUcAGl/vqlRWki3Kq/aQM0EDitzPuL2B7GarO3nUuxx9hHUN1NyZTv8KT8QGjmZLzTs1LPtXm9MOebmNKLaiR8i7ymJK53inptDii7XnM2Y2GJBtgg6tTkfrXwBBmt8Q/IpNws1BDtbS7vJIJFrrIAf5w6vZGkHgfTiJqTdOIsYqYel9cfZ34LJGac3M0VZ0CxEj03atmukbIOwGWvKekhopvc3ze/uW31WonoLIgxRaZymq7DkcfNE9EBGjnbB3RO+MP2rJUcIqYJOnp+WWvG5FEW8iquLEMCqXdcNY6X0o+KnFIINiD7Eu8XiZOKt1VnNxMJnXgI8u4DI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/pl-host-file
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
