env:
  global:
    - secure: cZrZLaOCF/Ts7aE5c90PF1PX4KZypvPCnN5Kd2u35GuKsljBpNkq1hS/rCKEiQXl7OPMGZGsm3ZF6m2lN2EM3hjCyDB6gDgThmbKjsR6k+7Y7ZJr8y3FtK9iERjTz+tcK1PHfF5Uyn1LPIpxYl0L91jk6cZz585mQURXIeYf7CsKkTLnrqAkDa9dnTdE5xBm+7e/3+hTg7RrFOZ2+YEFJ8GUkB5AWIH2w+bIAAxIB0GxcUB9Nizeby2rkmSaKb/I9nma1wwdLnJkEYA1trC74brcLKA4K1+la4h5B65rmwJ2+7R816YWAmLx966DM54D/K/Xo3zd/dwUWs4OaG8rZUInb6ZLWluPGG+Sweb/TMZxzGMjYJGp6iMml4usxa8PmbURHE44eK5luQPL8vX7edSn3LqlDmpZXGv97hKkuAKWISLZ1y7yJkhTUgEnPyXfi6vcWonVjhWDXw+nMSsBgt5kSQb7Y1G+uW43UjynEmxCfjeMd6WldqCTiw19SpXidAgNw9XvOTOVPVRitspcjoVrFLs83S794Lb6El873QeCeLom3b4lsWAIttpdkABtFfExc64xv5MtzVL8qiM5UB3tFe/qnyC3gxtNmwC9weJdvWuK6aBYUDWVOjw64HhM/3zEO0cMLF9PtxFWzmty2dUnS+BefLMDBUZ3LoMW+2o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/pl-host-file
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
