env:
  global:
    - secure: EzedLjyUaQNdAKHWYvrwpLwNEwAohQ7l+vgtI+YIuVzHzmoeO7S6puPeNAq8P0cwliBKSP4y0RUXCfZ+VXCEWA4widsRA3OVc4f6/9AtHK/c5xUQ0/b+sJ+kSE7MDVG3iz78F7U7tjvTMtnRbd6oVbN+knW6uj1qXVAWM9+TPA6AnaKXdftMJ0wHu+3gbcvtxCccoGUyPbB7vyvuSe9nq+P4L8mrZ1Rz2SWm64CBqTfs763ppJRd/9yPhkyNclCuBuLl2bkZmLRoW/e961p4sVl84Win7bgHtWg2Td0Lox8BR0NARm9G2yYhTsJFmsmKv+ARSiWDAgR5PoiI3V5QIstDcaed/XMLQUC2V5bevNBuqd0iRyHBLWknUEJBeMA82imZYC17QUMGjHWMDpQrvIHMWkgmMRACTHEnGocIf0rVoWR+I0+NnkGwzj9dwBeeh5FDiA1JqHfMrdpEL7CpDDo/gwnnB4c/iqZtXibhZ82IN4d7saWEbZDY/iWtKgwgQb10dMEN44x5GjdXlAeIjbnzrZLbeo3KhF5Lkhrf6HBj1CrWdwi8vp+TnAzhbRbOM+Z6qieHs+K9EGoYucgbxT6Rfsf+2/3BCtYJcxjAt/uYKH+GKq/bvIItnDCzlEqobjTU+BE7pwe5PTrw9s8D4QKw1Y/Hk0JaQCHI9TiHLaw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/pl-host-file
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
